In [1]:
import numpy as np


In [21]:
def log_transformation(images):

    images = np.log(np.where(images !=0, images, np.min(images[images != 0])))

    return images

In [22]:

uncond_samples = np.load(("data/unconditional/diffusion/model3_beta_min_max_01_20_random0_2250.npy"))
uncond_true_samples = log_transformation(np.load(("data/unconditional/true/unconditional_model3_range_1.6_smooth_1.6_2250.npy")))

In [32]:
np.max(uncond_samples[17,:,:,:])

3.511619806289673

In [31]:
np.min(uncond_samples[8,:,:,:])

-2.1525750160217285

In [20]:
uncond_true_samples[:,5]

array([325.96691137,   1.08024557,   1.76105316, ...,   0.        ,
         0.        ,   0.        ])

In [4]:
pixel_samples = uncond_samples[:,:,15,15]
pixel_samples[pixel_samples <= -2]

array([-2.05613065, -2.10000777, -2.56847024, -2.0071044 , -2.00060773,
       -3.03835058, -2.39333797, -2.14886308])

In [6]:
pixel_samples = uncond_samples[:,:,15,20]
pixel_samples[pixel_samples <= -1.8]

array([-2.02895999, -1.96409988, -2.09664845, -1.88274848, -1.80000257,
       -1.87451768, -2.07816076, -4.05363846, -1.851107  , -1.94222939,
       -2.00030279])

In [8]:
pixel_samples = uncond_samples[:,:,1,1]
pixel_samples[pixel_samples <= -2]

array([-2.27822089, -2.36340594])

In [9]:
pixel_samples = uncond_samples[:,:,9,9]
pixel_samples[pixel_samples <= -2]

array([-2.04106951, -2.23615527, -3.42918205, -2.03798652])

In [10]:
pixel_samples = uncond_samples[:,:,20,29]
pixel_samples[pixel_samples <= -2]

array([-2.07455373, -2.06174016, -2.01061273, -3.36501312])

In [14]:
pixel_samples = uncond_true_samples[:,20]
pixel_samples[pixel_samples <= -2]

array([], dtype=float64)

In [23]:
pixel_samples = uncond_true_samples[:,102]
pixel_samples[pixel_samples <= -2]

array([-2.09988038, -2.07556682, -2.06033457, -2.03024736, -2.88498289,
       -2.88498289, -2.88498289, -2.88498289, -2.88498289, -2.88498289,
       -2.88498289, -2.88498289, -2.88498289, -2.88498289, -2.88498289,
       -2.88498289, -2.88498289, -2.88498289, -2.88498289, -2.88498289,
       -2.88498289, -2.88498289, -2.88498289, -2.88498289, -2.88498289,
       -2.88498289, -2.88498289, -2.88498289, -2.88498289])

In [24]:
np.exp(-2.884)

0.055910672262727355